import { StudentProfile, StudentSchedule, RehearsalRoom, RoomBooking, RehearsalEvent, Song, ArtisticProject } from './shared';

export const INITIAL_PROJECTS: ArtisticProject[] = [
  {
    id: 'proj-wishes-2026',
    name: 'Ensamble Musical WISHES 2026',
    type: 'COMPANY_SEMESTER',
    campus: 'Tec Campus Laguna (Torreón)',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    status: 'ACTIVE',
    directorName: 'Prof. Alejandro Gallegos',
    description: 'Montaje oficial del Ensamble Musical de Arte y Cultura para la temporada de otoño 2026.',
    characters: [
      { id: 'char-1', name: 'Solista Vocal Principal', roleType: 'PRINCIPAL', assignedStudentId: 'std-2', assignedStudentName: 'Sofia Garza', notes: 'Guía de armonías y voz lead.' },
      { id: 'char-2', name: 'Primer Saxofón Alto (Lead)', roleType: 'SOLO', assignedStudentId: 'std-1', assignedStudentName: 'Mateo Hernández', notes: 'Solos improvisados en arreglos jazz.' },
      { id: 'char-3', name: 'Batería & Percusión Principal', roleType: 'PRINCIPAL', assignedStudentId: 'std-5', assignedStudentName: 'Carlos Elizondo', notes: 'Base rítmica.' },
    ],
    enrolledStudentIds: ['std-1', 'std-2', 'std-5'],
  },
  {
    id: 'proj-diade-muertos-2026',
    name: 'Espectáculo Tradiciones: Día de Muertos 2026',
    type: 'SPECIAL_EVENT',
    campus: 'Tec Campus Laguna (Torreón)',
    startDate: '2026-10-15',
    endDate: '2026-11-02',
    status: 'ACTIVE',
    directorName: 'Prof. Alejandro Gallegos',
    description: 'Magno evento de la Compañía en la explanada de la DAE con caracterizaciones de La Catrina y música en vivo.',
    characters: [
      { id: 'char-4', name: 'La Catrina (Voz Solista)', roleType: 'PRINCIPAL', assignedStudentId: 'std-2', assignedStudentName: 'Sofia Garza', notes: 'Vestuario caracterización completa.' },
      { id: 'char-5', name: 'Cuerpo de Danza Contemporánea', roleType: 'ENSEMBLE', assignedStudentId: 'std-3', assignedStudentName: 'Diego Villalobos', notes: 'Cuadro de Catrines.' },
    ],
    enrolledStudentIds: ['std-2', 'std-3'],
  },
  {
    id: 'proj-masterclass-2026',
    name: 'Masterclass de Canto & Técnica Vocal',
    type: 'EXTRA_MASTERCLASS',
    campus: 'Tec Campus Laguna (Torreón)',
    startDate: '2026-09-01',
    endDate: '2026-09-02',
    status: 'ACTIVE',
    directorName: 'Maestra Invitada Mónica Hoth',
    description: 'Taller de perfeccionamiento vocal y afinación escénica para vocalistas de la Compañía.',
    characters: [
      { id: 'char-6', name: 'Vocalista Activo Masterclass', roleType: 'SOLO', assignedStudentId: 'std-2', assignedStudentName: 'Sofia Garza', notes: 'Interpretación aria de prueba.' },
      { id: 'char-7', name: 'Vocalista Oyente', roleType: 'ENSEMBLE', assignedStudentId: 'std-4', assignedStudentName: 'Mariana Cantú', notes: 'Participante registrado.' },
    ],
    enrolledStudentIds: ['std-2', 'std-4'],
  },
  {
    id: 'proj-noche-mexicana-2025',
    name: 'Gala Noche Mexicana 2025',
    type: 'SPECIAL_EVENT',
    campus: 'Tec Campus Laguna (Torreón)',
    startDate: '2025-09-01',
    endDate: '2025-09-16',
    status: 'ARCHIVED',
    directorName: 'Prof. Alejandro Gallegos',
    description: 'Proyecto de celebración de fiestas patrias del año anterior.',
    characters: [
      { id: 'char-8', name: 'Solista Mariachi', roleType: 'PRINCIPAL', assignedStudentId: 'std-2', assignedStudentName: 'Sofia Garza', notes: 'Concierto en Auditorio Life.' },
    ],
    enrolledStudentIds: ['std-1', 'std-2'],
  },
];

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'std-1',
    name: 'Mateo Hernández',
    email: 'mateo.h@tec.mx',
    matricula: 'A01708821',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Saxofón Alto',
    createdAt: '2026-08-01',
  },
  {
    id: 'std-2',
    name: 'Sofia Garza',
    email: 'sofia.garza@gmail.com',
    matricula: 'A01709943',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'CANTO',
    section: 'Soprano',
    createdAt: '2026-08-02',
  },
  {
    id: 'std-3',
    name: 'Diego Villalobos',
    email: 'diego.v@tec.mx',
    matricula: 'A01712345',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'PENDING_APPROVAL',
    companyName: 'Comedia Musical 2026',
    discipline: 'BAILE',
    section: 'Danza Contemporánea',
    createdAt: '2026-08-08',
  },
  {
    id: 'std-4',
    name: 'Mariana Cantú',
    email: 'marianacantu@outlook.com',
    matricula: 'A01799881',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'PENDING_APPROVAL',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Trompeta 1',
    createdAt: '2026-08-09',
  },
  {
    id: 'std-5',
    name: 'Carlos Elizondo',
    email: 'carlos.e@tec.mx',
    matricula: 'A01755443',
    campus: 'Tec Campus Monterrey',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Batería & Percusión',
    createdAt: '2026-08-03',
  },
];

export const INITIAL_SCHEDULES: StudentSchedule[] = [
  {
    studentId: 'std-1',
    slots: [
      { id: 's1', day: 'LUNES', startTime: '09:00', endTime: '11:00', courseName: 'Cálculo Diferencial', isAcademicClass: true },
      { id: 's2', day: 'LUNES', startTime: '13:00', endTime: '15:00', courseName: 'Física I', isAcademicClass: true },
      { id: 's3', day: 'MARTES', startTime: '11:00', endTime: '13:00', courseName: 'Programación Orientada a Objetos', isAcademicClass: true },
    ],
  },
];

export const INITIAL_ROOMS: RehearsalRoom[] = [
  {
    id: 'room-101',
    name: 'Salón de Ensamble A-101',
    building: 'Edificio de Difusión Cultural (DAE)',
    capacity: 35,
    equipment: ['Piano Yamaha C7', 'Batería Pearl Vision', 'Sistema PA 2000W', 'Atriles (30)'],
    status: 'AVAILABLE',
  },
  {
    id: 'room-102',
    name: 'Sala de Danza & Expresión B-202',
    building: 'Pabellón Cultural Tec',
    capacity: 50,
    equipment: ['Piso Flotante de Madera', 'Espejos de Muro Completo', 'Barras de Ballet'],
    status: 'AVAILABLE',
  },
];

export const INITIAL_ROOM_BOOKINGS: RoomBooking[] = [
  {
    id: 'bk-1',
    roomId: 'room-101',
    roomName: 'Salón de Ensamble A-101',
    requestedByStudentId: 'std-1',
    studentName: 'Mateo Hernández',
    companyName: 'Ensamble Musical Tec',
    purpose: 'Ensayo seccional de Vientos',
    date: '2026-08-12',
    startTime: '17:00',
    endTime: '19:00',
    status: 'APPROVED',
    qrPermissionCode: 'PERMISO-TEC-889021',
  },
];

export const INITIAL_REHEARSALS: RehearsalEvent[] = [
  {
    id: 'reh-1',
    title: 'Ensayo General - WISHES 2026',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    targetSections: [],
    date: '2026-08-13',
    startTime: '17:00',
    endTime: '20:00',
    location: 'Salón de Ensamble A-101',
    description: 'Ensayo de montaje completo para los temas de WISHES. Llevar partituras impresas o en tablet.',
    qrCheckInCode: 'QR-ENSAYO-WISHES-2026',
    projectId: 'proj-wishes-2026',
  },
  {
    id: 'reh-2',
    title: 'Caracterización & Canto - Día de Muertos',
    companyName: 'Ensamble Musical Tec',
    discipline: 'CANTO',
    targetSections: ['Soprano', 'Tenor', 'Alto'],
    date: '2026-10-20',
    startTime: '16:00',
    endTime: '18:00',
    location: 'Estudio de Canto & Vientos C-05',
    description: 'Ajuste de vestuario y afinación de arias del espectáculo.',
    qrCheckInCode: 'QR-CANTO-MUERTOS-8821',
    projectId: 'proj-diade-muertos-2026',
  },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song-1',
    title: 'Huapango de Moncayo (Arr. WISHES 2026)',
    composer: 'José Pablo Moncayo',
    companyName: 'Ensamble Musical Tec',
    genre: 'Sinfónico / Fusión',
    key: 'C Mayor',
    durationSeconds: 380,
    sheets: [
      { id: 'sh-1', instrumentOrVoice: 'Partitura Director (Full Score)', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
      { id: 'sh-2', instrumentOrVoice: 'Saxofón Alto 1', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
    ],
    guides: [
      { id: 'g-1', title: 'Pista Completa Maqueta (Tutti)', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', bpm: 128 },
    ],
    createdAt: '2026-08-01',
    projectId: 'proj-wishes-2026',
  },
];
