import { StudentProfile, StudentSchedule, RehearsalRoom, RoomBooking, RehearsalEvent, Song } from './shared';

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 'std-1',
    name: 'Mateo Hernández',
    email: 'mateo.h@tec.mx',
    matricula: 'A01708821',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Saxofón Alto',
    phone: '811-234-5678',
    createdAt: '2026-08-01',
  },
  {
    id: 'std-2',
    name: 'Sofia Garza',
    email: 'sofia.garza@gmail.com',
    matricula: 'A01709943',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'CANTO',
    section: 'Soprano',
    phone: '818-765-4321',
    createdAt: '2026-08-02',
  },
  {
    id: 'std-3',
    name: 'Diego Villalobos',
    email: 'diego.v@tec.mx',
    matricula: 'A01712345',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'PENDING_APPROVAL',
    companyName: 'Comedia Musical 2026',
    discipline: 'BAILE',
    section: 'Danza Contemporánea',
    phone: '811-999-8877',
    createdAt: '2026-08-08',
  },
  {
    id: 'std-4',
    name: 'Mariana Cantú',
    email: 'marianacantu@outlook.com',
    matricula: 'A01799881',
    campus: 'Tec Campus Laguna (Torreón)',
    role: 'STUDENT',
    status: 'PENDING_APPROVAL',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Trompeta 1',
    phone: '818-444-2211',
    createdAt: '2026-08-09',
  },
  {
    id: 'std-5',
    name: 'Carlos Elizondo',
    email: 'carlos.e@tec.mx',
    matricula: 'A01755443',
    campus: 'Tec Campus Monterrey',
    role: 'STUDENT',
    status: 'ACTIVE',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    section: 'Batería & Percusión',
    phone: '811-555-1234',
    createdAt: '2026-08-03',
  },
];

export const INITIAL_SCHEDULES: StudentSchedule[] = [
  {
    studentId: 'std-1',
    updatedAt: '2026-08-05',
    slots: [
      { id: 's1', day: 'LUNES', startTime: '09:00', endTime: '11:00', courseName: 'Cálculo Diferencial', isAcademicClass: true },
      { id: 's2', day: 'LUNES', startTime: '13:00', endTime: '15:00', courseName: 'Física I', isAcademicClass: true },
      { id: 's3', day: 'MARTES', startTime: '11:00', endTime: '13:00', courseName: 'Programación Orientada a Objetos', isAcademicClass: true },
      { id: 's4', day: 'MIERCOLES', startTime: '09:00', endTime: '11:00', courseName: 'Cálculo Diferencial', isAcademicClass: true },
      { id: 's5', day: 'JUEVES', startTime: '11:00', endTime: '13:00', courseName: 'Programación Orientada a Objetos', isAcademicClass: true },
      { id: 's6', day: 'VIERNES', startTime: '15:00', endTime: '17:00', courseName: 'Laboratorio de Innovación', isAcademicClass: true },
    ],
  },
  {
    studentId: 'std-2',
    updatedAt: '2026-08-06',
    slots: [
      { id: 's7', day: 'LUNES', startTime: '09:00', endTime: '11:00', courseName: 'Derecho Constitucional', isAcademicClass: true },
      { id: 's8', day: 'MARTES', startTime: '15:00', endTime: '17:00', courseName: 'Ética y Filosofía', isAcademicClass: true },
      { id: 's9', day: 'MIERCOLES', startTime: '09:00', endTime: '11:00', courseName: 'Derecho Constitucional', isAcademicClass: true },
      { id: 's10', day: 'JUEVES', startTime: '15:00', endTime: '17:00', courseName: 'Ética y Filosofía', isAcademicClass: true },
    ],
  },
  {
    studentId: 'std-5',
    updatedAt: '2026-08-07',
    slots: [
      { id: 's11', day: 'LUNES', startTime: '11:00', endTime: '13:00', courseName: 'Economía Tec', isAcademicClass: true },
      { id: 's12', day: 'MARTES', startTime: '09:00', endTime: '11:00', courseName: 'Estadística Aplicada', isAcademicClass: true },
      { id: 's13', day: 'JUEVES', startTime: '09:00', endTime: '11:00', courseName: 'Estadística Aplicada', isAcademicClass: true },
      { id: 's14', day: 'VIERNES', startTime: '11:00', endTime: '13:00', courseName: 'Economía Tec', isAcademicClass: true },
    ],
  },
];

export const INITIAL_ROOMS: RehearsalRoom[] = [
  {
    id: 'room-101',
    name: 'Salón de Ensamble A-101',
    building: 'Edificio de Difusión Cultural (DAE)',
    capacity: 35,
    equipment: ['Piano Yamaha C7', 'Batería Pearl Vision', 'Sistema PA 2000W', 'Atriles (30)'],
    status: 'AVAILABLE',
  },
  {
    id: 'room-102',
    name: 'Sala de Danza & Expresión B-202',
    building: 'Pabellón Cultural Tec',
    capacity: 50,
    equipment: ['Piso Flotante de Madera', 'Espejos de Muro Completo', 'Barras de Ballet', 'Sound System Bluetooth'],
    status: 'AVAILABLE',
  },
  {
    id: 'room-103',
    name: 'Estudio de Canto & Vientos C-05',
    building: 'Auditorio Luis Elizondo (Sótano)',
    capacity: 15,
    equipment: ['Piano Acústico Vertical', 'Aislamiento Acústico Premium', 'Micrófonos Shure SM58 (6)'],
    status: 'AVAILABLE',
  },
];

export const INITIAL_ROOM_BOOKINGS: RoomBooking[] = [
  {
    id: 'bk-1',
    roomId: 'room-101',
    roomName: 'Salón de Ensamble A-101',
    requestedByStudentId: 'std-1',
    studentName: 'Mateo Hernández',
    companyName: 'Ensamble Musical Tec',
    purpose: 'Ensayo seccional de Vientos (Saxofones y Trompetas)',
    date: '2026-08-12',
    startTime: '17:00',
    endTime: '19:00',
    status: 'APPROVED',
    qrPermissionCode: 'PERMISO-TEC-889021',
    approvedBy: 'Director R. Cantú',
  },
  {
    id: 'bk-2',
    roomId: 'room-102',
    roomName: 'Sala de Danza & Expresión B-202',
    requestedByStudentId: 'std-3',
    studentName: 'Diego Villalobos',
    companyName: 'Comedia Musical 2026',
    purpose: 'Ensayo de Coreografía Números 3 y 4',
    date: '2026-08-14',
    startTime: '18:00',
    endTime: '20:00',
    status: 'PENDING',
  },
];

export const INITIAL_REHEARSALS: RehearsalEvent[] = [
  {
    id: 'reh-1',
    title: 'Ensayo General - Gala de Invierno Tec',
    companyName: 'Ensamble Musical Tec',
    discipline: 'MUSICA',
    targetSections: [],
    date: '2026-08-13',
    startTime: '17:00',
    endTime: '20:00',
    location: 'Salón de Ensamble A-101',
    description: 'Ensayo de montaje completo para los temas de la Gala. Llevar partituras impresas o en tablet.',
    qrCheckInCode: 'QR-ENSAYO-GALA-2026',
  },
  {
    id: 'reh-2',
    title: 'Seccional de Canto & Armonía Vocal',
    companyName: 'Ensamble Musical Tec',
    discipline: 'CANTO',
    targetSections: ['Soprano', 'Tenor', 'Alto'],
    date: '2026-08-15',
    startTime: '16:00',
    endTime: '18:00',
    location: 'Estudio de Canto & Vientos C-05',
    description: 'Ajuste de afinación y matices en voces de acompañamiento.',
    qrCheckInCode: 'QR-CANTO-VOCAL-8821',
  },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song-1',
    title: 'Huapango de Moncayo (Arr. Big Band Tec)',
    composer: 'José Pablo Moncayo',
    arranger: 'Prof. Roberto Cantú',
    companyName: 'Ensamble Musical Tec',
    genre: 'Sinfónico / Fusión',
    key: 'C Mayor',
    durationSeconds: 380,
    sheets: [
      { id: 'sh-1', instrumentOrVoice: 'Partitura Director (Full Score)', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
      { id: 'sh-2', instrumentOrVoice: 'Saxofón Alto 1', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf', keySignature: 'Eb' },
      { id: 'sh-3', instrumentOrVoice: 'Trompeta 1', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf', keySignature: 'Bb' },
      { id: 'sh-4', instrumentOrVoice: 'Voz Soprano Guía', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
    ],
    guides: [
      { id: 'g-1', title: 'Pista Completa Maqueta (Tutti)', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', bpm: 128 },
      { id: 'g-2', title: 'Guía Acompañamiento Piano & Bajo', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', bpm: 128 },
    ],
    createdAt: '2026-08-01',
  },
  {
    id: 'song-2',
    title: 'Uptown Funk (Medley Danza & Ensamble)',
    composer: 'Mark Ronson / Bruno Mars',
    arranger: 'Lalo Rodríguez',
    companyName: 'Ensamble Musical Tec',
    genre: 'Funk / Pop',
    key: 'D Menor',
    durationSeconds: 260,
    sheets: [
      { id: 'sh-5', instrumentOrVoice: 'Batería & Percusión', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
      { id: 'sh-6', instrumentOrVoice: 'Sección Metales (Brass Score)', pdfUrl: 'https://pdfobject.com/pdf/sample.pdf' },
    ],
    guides: [
      { id: 'g-3', title: 'Pista de Referencia Ensayo Baile', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', bpm: 115 },
    ],
    createdAt: '2026-08-04',
  },
];
